<?php

namespace Omalizadeh\MultiPayment\Tests;

use Omalizadeh\MultiPayment\Invoice;

class InvoiceTest extends TestCase
{
    public function testTomansToRialsAutoConversion(): void
    {
        $invoice = new Invoice(12000);

        $this->assertEquals(120000, $invoice->getAmount());
        $this->assertEquals(12000, $invoice->getAmountInTomans());
    }

    public function testRialsToTomansAutoConversion(): void
    {
        config(['multipayment.convert_to_rials' => false]);

        $invoice = new Invoice(12000);

        $this->assertEquals(12000, $invoice->getAmount());
        $this->assertEquals(1200, $invoice->getAmountInTomans());
    }

    public function testUuidIsAutoGenerated(): void
    {
        $invoice = new Invoice(111);

        $this->assertNotEmpty($invoice->getUuid());
        $this->assertIsString($invoice->getUuid());
    }

    public function testUuidIsRandom(): void
    {
        $firstInvoice = new Invoice(111);
        $secondInvoice = new Invoice(222);

        $this->assertNotEquals($firstInvoice->getUuid(), $secondInvoice->getUuid());
    }

    public function testStringAmountIsAcceptable(): void
    {
        config(['multipayment.convert_to_rials' => false]);

        $invoice = new Invoice('110.99');

        $this->assertEquals(110.99, $invoice->getAmount());
    }
}
